apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-greeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-greeter
  template:
    metadata:
      labels:
        app: rust-greeter
    spec:
      containers:
      - name: rust-greeter
        image: rust-greeter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
